#!/usr/bin/env ruby

require 'css_parser'
require 'yaml'

require "#{File.dirname(__FILE__)}/src/splicer.rb"

include CssParser
include CssSplicer

begin
  config = File.open('./config.yaml') { |file| YAML.load(file) }
rescue
  puts "You need a config.yaml file!"
  exit
end

# handle each input file
config['input'].each do |in_conf|
  p = CssSplicer::Splicer.input_parsers.push(CssParser::Parser.new).last
  if in_conf['type'] == 'file'
    p.load_file!(in_conf['uri'], Dir.getwd)
  else
    p.load_uri!(in_conf['uri'])
  end
end

# create each output
config['output'].each do |out_conf|
  p = CssSplicer::Splicer.new(out_conf['name'])

  p.add_allowed_properties!(out_conf['allowed_properties'])

  p.combine_rules = out_conf['combine_rules']
  p.combine_selectors = out_conf['combine_selectors']

  CssSplicer::Splicer.input_parsers.each do |css|
    p.add_valid_rules!(css)
  end
  File.open("./output/#{p.name}", 'w') do |file|
    file.write(p.to_s)
    puts "wrote #{p.name}"
  end
end
